# Generated by Django 5.0.6 on 2024-05-23 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_type',
            new_name='notification_types',
        ),
    ]
