# Generated by Django 5.0.6 on 2024-05-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='blog',
            new_name='comment',
        ),
    ]
