# Generated by Django 5.0.6 on 2024-05-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='muted',
            field=models.BooleanField(default=False),
        ),
    ]
